theme = "bigspring-light"
baseURL = 'https://biaslab.github.io/rxinfer-website/'
languageCode = "en"
languageName = "English"
title = 'RxInfer.jl'
copyright = "Design By [Themefisher](https://themefisher.com/) Develop By [Gethugothemes](https://gethugothemes.com/)"


[params]
    logo = "images/rxinfer.svg"
    favicon = "images/favicon.svg"
    logo_width = 100
    author = "BIASlab"
    copyright = "Â© BIASlab, 2022"
    footer_menu_left = "Ecosystem"
    footer_menu_middle = "Supported by"
    footer_content = "Follow Us"
    image = "images/favicon.svg"
    jlhighlight = "js/julia.highlight.js"
    custom_js = []


    [[params.social]]
        icon = "fab fa-youtube"
        link = "//youtube.com/channel/UCd1ftkOXIQ8MstIHosEDdaw"


    [[params.social]]
        icon = "fab fa-github"
        link = "//github.com/biaslab/rxinfer.jl"


    [[params.social]]
        icon = "fas fa-diagram-project"
        link = "//biaslab.github.io/"

[author]
  name = "BIASlab"
  email = ""
  link = "https://biaslab.github.io/"

[menu]
    
    [[menu.footer_left]]
    name = "Rocket.jl"
    url = "https://github.com/biaslab/Rocket.jl"
    weight = 1

    [[menu.footer_left]]
    name = "ReactiveMP.jl"
    url = "https://github.com/biaslab/ReactiveMP.jl"
    weight = 2

    [[menu.footer_left]]
    name = "GraphPPL.jl"
    url = "https://github.com/biaslab/GraphPPL.jl"
    weight = 1

    [[menu.footer_middle]]
    name = "NWO"
    pre = "images/NWO.png"
    url = "https://www.nwo.nl/en"
    weight = 2

    [[menu.footer_middle]]
    name = "GN Hearing"
    pre = "images/gn.png"
    url = "https://www.resound.com/nl-nl/"
    weight = 3


    [[menu.main]]
    name = "Get Started"
    url = "https://biaslab.github.io/RxInfer.jl/stable/man/getting-started/"
    weight = 1

    [[menu.main]]
    name = "Documentation"
    pre = ""
    url = "https://biaslab.github.io/RxInfer.jl/stable/"
    weight = 2

    [[menu.main]]
    name = "Papers"
    pre = ""
    url = "https://biaslab.github.io/publication/"
    weight = 4

    [[menu.main]]
    name = "Examples"
    url = "https://biaslab.github.io/RxInfer.jl/stable/examples/overview/"
    weight = 3

    [[menu.main]]
    name = "Team"
    pre = ""
    weight = 5
    url = "https://biaslab.github.io/team/"
    # url = "/team"

    [[menu.main]]
    name = "Contact"
    pre = ""
    weight = 6
    url = "/contact"

    [[menu.main]]
    name = "GitHub"
    pre = "fab fa-github"
    url = "https://github.com/biaslab/RxInfer.jl"
    weight = 7

[markup]
    [markup.highlight]
    noClasses = false




# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/fontawesome.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/brands.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/solid.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/regular.min.css"